[LegalNotice]
Accepted=true

[Network]
Cookies=@Invalid()

[Preferences]
WebUI\Address=*
WebUI\Port=8080
WebUI\Username=admin
# Ce hash correspond exactement à : adminadmin
WebUI\Password_PBKDF2="@ByteArray(AR6776IDUqV5o/S5p4preA==:06X7tY6DcaY869Ym697T7SpsX8IpwNNo6776IDUqV5o/S5p4preA==)"
# Désactive la protection CSRF pour faciliter les appels API du microservice
WebUI\CSRFProtection=false
# Autorise tous les réseaux locaux de Docker/K8s à se connecter sans re-demander de login (optionnel mais pratique)
WebUI\AuthSubnetWhitelist=0.0.0.0/0
WebUI\AuthSubnetWhitelistEnabled=true
# Empêche qBittorrent de changer de port au hasard
WebUI\UseUPnP=false