services:

  bd:
    image: postgres:16
    container_name: fleeceTV_bd
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB} 
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432" 
    volumes: 
      - ${DB_DATA_PATH}:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 1m30s
      timeout: 30s
      retries: 5


  redis:
    image: redis:7
    container_name: fleeceTV_redis
    restart: always
    command: redis-server --appendonly no  --maxmemory 512mb --maxmemory-policy allkeys-lru --save ""


  api:
    build:
      context: services/api
      dockerfile: Dockerfile
    container_name: fleeceTV_api
    restart: always
    depends_on:
      - bd
      - redis
    ports:
      - "8000:8000"
    environment:
      MEDIA_PATH: /media
      DATABASE_URL: ${DATABASE_URL}
      TMDB_API_KEY: ${TMDB_API_KEY}
      TMDB_BASE_URL: ${TMDB_BASE_URL}
      JACKETT_KEY: ${JACKETT_KEY}
      VF_INDEXER: ${VF_INDEXER}
      ENG_INDEXER: ${ENG_INDEXER} 
    volumes:
      - ${NAS_PATH}:/media:rw
      - .services/api/config/alembic:/alembic
      - .services/api/alembic.ini:/alembic.ini
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload


  worker:
    build:
      context: services/worker 
      dockerfile: Dockerfile
    container_name: fleeceTV_worker
    restart: always
    depends_on:
      - redis
      - api
    environment:
      - MEDIA_PATH:/media
    volumes:
      - ${NAS_PATH}:/media:rw
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
      - net.ipv6.conf.default.disable_ipv6=1



  jackett:
    image: lscr.io/linuxserver/jackett
    container_name: fleeceTV_jackett
    restart: unless-stopped
    ports:
      - "9117:9117"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
    volumes:
      - ./services/jackett:/config


  portal:
    build:
      context: services/portal
      dockerfile: Dockerfile 
    container_name: fleeceTV_portal
    environment:
      FLEECETV_API_URL: ${FLEECETV_API_URL}
    restart: always
    depends_on:
      - api
    ports:
      - "8080:80"

