services:

  fleecetv_bd:
    image: postgres:16
    container_name: fleeceTV_bd
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB} 
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432" 
    volumes: 
      - ${DB_DATA_PATH}:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 1m30s
      timeout: 30s
      retries: 5


  fleecetv_api:
    build:
      context: .
      dockerfile: src/api/Dockerfile
    container_name: fleeceTV_api
    restart: always
    depends_on:
      - fleecetv_bd
    ports:
      - "8000:8000"
    environment:
      MEDIA_PATH: /media
    volumes:
      - ${NAS_PATH}:/media:ro


  fleecetv_portal:
    build:
      context: .
      dockerfile: src/portal/Dockerfile 
    container_name: fleeceTV_portal
    environment:
      FLEECETV_API_URL: ${FLEECETV_API_URL}
    restart: always
    depends_on:
      - fleecetv_api
    ports:
      - "8080:8080"

