"""update pipelineDB(Pipeline)

Revision ID: 406f544c29d6
Revises: 9b47d15375ac
Create Date: 2026-02-23 19:22:59.025077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '406f544c29d6'
down_revision: Union[str, Sequence[str], None] = '9b47d15375ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pipelines', 'target_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pipelines', 'target_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
